(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "dash")
;; (depends-on "expand-region")
(depends-on "f")
;; (depends-on "flycheck")
;; (depends-on "flycheck-cask")
(depends-on "popwin")
(depends-on "s")
(depends-on "smartparens")
(depends-on "pallet")
;; (depends-on "minimap")
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "undo-tree")
(depends-on "smooth-scroll")
(depends-on "volatile-highlights")
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "region-bindings-mode")
(depends-on "color-theme-solarized")
(depends-on "rainbow-delimiters")
(depends-on "sequential-command")

;; XXX-mode
(depends-on "rust-mode")
(depends-on "dockerfile-mode")
(depends-on "kotlin-mode")